using Microsoft.Xna.Framework;

namespace ChainsawManMod.Content.Players
{
	// The rows of the Chainsaw Devil sprite sheets, top to bottom.
	public enum DevilAnim
	{
		Idle,
		Walk,
		Run,
		Jump,
		Crouch,
		Attack1,
		Attack2,
		Attack3,
		Attack4,
		Attack5,
		AirAttack1,
		AirAttack2,
		AirAttack3,
		Damage,
		Attack6 // only on the Hero of Hell sheet
	}

	// One sprite sheet generated by tools/clean_sprite_sheet.py.
	// Every frame sits in a CellWidth x CellHeight cell, with the character's feet at the bottom centre of the cell.
	public class DevilSheet
	{
		public string TexturePath { get; init; }
		public int CellWidth { get; init; }
		public int CellHeight { get; init; }

		// Frames per row, in DevilAnim order. 0 = the sheet doesn't have that row.
		public int[] FrameCounts { get; init; }

		// Jump frames to show when rising fast, rising, near the top, and falling.
		public int[] JumpFrames { get; init; }

		// Frame held while crouching, and how many frames at the start of the Damage row are the "hit" reaction.
		public int CrouchFrame { get; init; }
		public int HurtFrames { get; init; }

		public int FrameCount(DevilAnim anim) {
			int row = (int)anim;
			return row < FrameCounts.Length ? FrameCounts[row] : 0;
		}

		public bool Has(DevilAnim anim) => FrameCount(anim) > 0;

		public Rectangle GetFrame(DevilAnim anim, int frame) {
			int count = FrameCount(anim);
			if (count <= 0) {
				anim = DevilAnim.Idle;
				count = FrameCount(anim);
			}
			return new Rectangle(frame % count * CellWidth, (int)anim * CellHeight, CellWidth, CellHeight);
		}
	}

	public static class ChainsawDevilAnimation
	{
		// Starter Cord and Revved Starter Cord forms.
		public static readonly DevilSheet ChainsawDevil = new() {
			TexturePath = "ChainsawManMod/Content/Players/ChainsawDevilSheet",
			CellWidth = 94,
			CellHeight = 58,
			FrameCounts = new[] { 6, 8, 8, 7, 5, 8, 7, 13, 6, 8, 5, 5, 6, 9, 0 },
			JumpFrames = new[] { 2, 3, 4, 5 },
			CrouchFrame = 1,
			HurtFrames = 4
		};

		// Hero of Hell's Cord form.
		public static readonly DevilSheet HeroOfHell = new() {
			TexturePath = "ChainsawManMod/Content/Players/HeroOfHellSheet",
			CellWidth = 144,
			CellHeight = 68,
			FrameCounts = new[] { 6, 7, 7, 7, 6, 7, 6, 17, 6, 8, 7, 5, 6, 15, 17 },
			JumpFrames = new[] { 0, 2, 3, 4 },
			CrouchFrame = 3,
			HurtFrames = 3
		};

		public static DevilSheet ForTier(int formTier) => formTier >= 3 ? HeroOfHell : ChainsawDevil;

		public static readonly DevilAnim[] GroundAttacks = { DevilAnim.Attack1, DevilAnim.Attack2, DevilAnim.Attack3, DevilAnim.Attack4, DevilAnim.Attack5, DevilAnim.Attack6 };
		public static readonly DevilAnim[] AirAttacks = { DevilAnim.AirAttack1, DevilAnim.AirAttack2, DevilAnim.AirAttack3 };
	}
}
