using ChainsawManMod.Content.Hybrids;
using Microsoft.Xna.Framework;

namespace ChainsawManMod.Content.Players
{
	// The rows of the Chainsaw Devil sprite sheets, top to bottom.
	public enum DevilAnim
	{
		Idle,
		Walk,
		Run,
		Jump,
		Crouch,
		Attack1,
		Attack2,
		Attack3,
		Attack4,
		Attack5,
		AirAttack1,
		AirAttack2,
		AirAttack3,
		Damage,
		Attack6 // only on the Hero of Hell sheet
	}

	// One sprite sheet generated by tools/clean_sprite_sheet.py.
	// Every frame sits in a CellWidth x CellHeight cell, with the character's feet at the bottom centre of the cell.
	public class DevilSheet
	{
		public string TexturePath { get; init; }
		public int CellWidth { get; init; }
		public int CellHeight { get; init; }

		// Frames per row, in DevilAnim order. 0 = the sheet doesn't have that row.
		public int[] FrameCounts { get; init; }

		// Jump frames to show when rising fast, rising, near the top, and falling.
		public int[] JumpFrames { get; init; }

		// Frame held while crouching, and how many frames at the start of the Damage row are the "hit" reaction.
		public int CrouchFrame { get; init; }
		public int HurtFrames { get; init; }

		public int FrameCount(DevilAnim anim) {
			int row = (int)anim;
			return row < FrameCounts.Length ? FrameCounts[row] : 0;
		}

		public bool Has(DevilAnim anim) => FrameCount(anim) > 0;

		public Rectangle GetFrame(DevilAnim anim, int frame) {
			int count = FrameCount(anim);
			if (count <= 0) {
				anim = DevilAnim.Idle;
				count = FrameCount(anim);
			}
			return new Rectangle(frame % count * CellWidth, (int)anim * CellHeight, CellWidth, CellHeight);
		}
	}

	public static class ChainsawDevilAnimation
	{
		// Starter Cord and Revved Starter Cord forms.
		public static readonly DevilSheet ChainsawDevil = new() {
			TexturePath = "ChainsawManMod/Content/Players/ChainsawDevilSheet",
			CellWidth = 94,
			CellHeight = 58,
			FrameCounts = new[] { 6, 8, 8, 7, 5, 8, 7, 13, 6, 8, 5, 5, 6, 9, 0 },
			JumpFrames = new[] { 2, 3, 4, 5 },
			CrouchFrame = 1,
			HurtFrames = 4
		};

		// Hero of Hell's Cord form.
		public static readonly DevilSheet HeroOfHell = new() {
			TexturePath = "ChainsawManMod/Content/Players/HeroOfHellSheet",
			CellWidth = 144,
			CellHeight = 68,
			FrameCounts = new[] { 6, 7, 7, 7, 6, 7, 6, 17, 6, 8, 7, 5, 6, 15, 17 },
			JumpFrames = new[] { 0, 2, 3, 4 },
			CrouchFrame = 3,
			HurtFrames = 3
		};

		public static DevilSheet ForTier(int formTier) => formTier >= 3 ? HeroOfHell : ChainsawDevil;

		// Hybrid forms without real art yet: placeholder sheets drawn by tools/generate_sprites.py, all with the same layout.
		// Replace a PNG with real art using the same cells and rows (or give it its own DevilSheet here).
		private static DevilSheet Placeholder(string name) => new() {
			TexturePath = $"ChainsawManMod/Content/Players/Hybrid{name}Sheet",
			CellWidth = 48,
			CellHeight = 52,
			FrameCounts = new[] { 4, 6, 6, 4, 2, 4, 4, 0, 0, 0, 4, 0, 0, 3, 0 },
			JumpFrames = new[] { 0, 1, 2, 3 },
			CrouchFrame = 1,
			HurtFrames = 3
		};

		// Reze (Bomb form): cleaned from art/reze_source.png by tools/clean_sprite_sheet.py.
		private static readonly DevilSheet Bomb = new() {
			TexturePath = "ChainsawManMod/Content/Players/HybridBombSheet",
			CellWidth = 64,
			CellHeight = 46,
			FrameCounts = new[] { 3, 5, 6, 5, 2, 7, 8, 5, 6, 4, 6, 5, 3, 6, 6 },
			JumpFrames = new[] { 0, 1, 2, 3 },
			CrouchFrame = 0,
			HurtFrames = 3
		};

		// Katana Man: cleaned from art/katana_man_source.png by tools/clean_sprite_sheet.py.
		private static readonly DevilSheet Katana = new() {
			TexturePath = "ChainsawManMod/Content/Players/HybridKatanaSheet",
			CellWidth = 62,
			CellHeight = 43,
			FrameCounts = new[] { 6, 6, 6, 6, 2, 8, 8, 4, 8, 9, 10, 2, 0, 6, 8 },
			JumpFrames = new[] { 1, 2, 3, 4 },
			CrouchFrame = 0,
			HurtFrames = 3
		};
		private static readonly DevilSheet Bow = Placeholder("Bow");
		private static readonly DevilSheet Flamethrower = Placeholder("Flamethrower");
		private static readonly DevilSheet Sword = Placeholder("Sword");
		private static readonly DevilSheet Spear = Placeholder("Spear");
		private static readonly DevilSheet Whip = Placeholder("Whip");

		public static DevilSheet ForHybrid(HybridType hybrid) => hybrid switch {
			HybridType.Bomb => Bomb,
			HybridType.Katana => Katana,
			HybridType.Bow => Bow,
			HybridType.Flamethrower => Flamethrower,
			HybridType.Sword => Sword,
			HybridType.Spear => Spear,
			HybridType.Whip => Whip,
			_ => ChainsawDevil
		};

		public static readonly DevilAnim[] GroundAttacks = { DevilAnim.Attack1, DevilAnim.Attack2, DevilAnim.Attack3, DevilAnim.Attack4, DevilAnim.Attack5, DevilAnim.Attack6 };
		public static readonly DevilAnim[] AirAttacks = { DevilAnim.AirAttack1, DevilAnim.AirAttack2, DevilAnim.AirAttack3 };
	}
}
