#!/usr/bin/env python3
"""Rebuilds shell/games/catalog.js from every shell/games/<id>/meta.json.

A game is listed only when its folder has index.html, thumb.svg and meta.json.
Run it after adding or changing a game:  python3 blockos/tools/gen-catalog.py
"""
import json
import pathlib
import sys

GAMES = pathlib.Path(__file__).resolve().parent.parent / "shell" / "games"
REQUIRED = ("id", "title", "genre", "description", "controls")

entries = []
for meta_path in sorted(GAMES.glob("*/meta.json")):
    folder = meta_path.parent
    if not (folder / "index.html").exists() or not (folder / "thumb.svg").exists():
        print(f"skipping {folder.name}: needs index.html and thumb.svg", file=sys.stderr)
        continue
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    missing = [k for k in REQUIRED if not meta.get(k)]
    if missing or meta["id"] != folder.name:
        print(f"skipping {folder.name}: bad meta.json (missing {missing} or id mismatch)", file=sys.stderr)
        continue
    meta.setdefault("scoreLabel", "Best score")
    meta.setdefault("lowerIsBetter", False)
    meta.setdefault("color", "#3b82f6")
    entries.append(meta)

entries.sort(key=lambda g: g["title"].lower())
body = ",\n".join("  " + json.dumps(e, ensure_ascii=False) for e in entries)
(GAMES / "catalog.js").write_text(
    "/* Generated by blockos/tools/gen-catalog.py from games/<id>/meta.json. Don't edit by hand. */\n"
    f"window.BLOCKOS_GAMES = [\n{body}\n];\n",
    encoding="utf-8",
)
print(f"catalog.js: {len(entries)} games")
